/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestingRouteImport } from './routes/testing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as JoinRouteImport } from './routes/join'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiIpnRouteImport } from './routes/api.ipn'
import { Route as ApiCheckoutRatesRouteImport } from './routes/api.checkout.rates'
import { Route as ApiCheckoutCreateRouteImport } from './routes/api.checkout.create'

const TestingRoute = TestingRouteImport.update({
  id: '/testing',
  path: '/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIpnRoute = ApiIpnRouteImport.update({
  id: '/api/ipn',
  path: '/api/ipn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRatesRoute = ApiCheckoutRatesRouteImport.update({
  id: '/api/checkout/rates',
  path: '/api/checkout/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutCreateRoute = ApiCheckoutCreateRouteImport.update({
  id: '/api/checkout/create',
  path: '/api/checkout/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/join': typeof JoinRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testing': typeof TestingRoute
  '/api/ipn': typeof ApiIpnRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/checkout/create': typeof ApiCheckoutCreateRoute
  '/api/checkout/rates': typeof ApiCheckoutRatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/join': typeof JoinRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testing': typeof TestingRoute
  '/api/ipn': typeof ApiIpnRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/checkout/create': typeof ApiCheckoutCreateRoute
  '/api/checkout/rates': typeof ApiCheckoutRatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/join': typeof JoinRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testing': typeof TestingRoute
  '/api/ipn': typeof ApiIpnRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/api/checkout/create': typeof ApiCheckoutCreateRoute
  '/api/checkout/rates': typeof ApiCheckoutRatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/checkout'
    | '/checkout-success'
    | '/join'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/testing'
    | '/api/ipn'
    | '/products/$slug'
    | '/api/checkout/create'
    | '/api/checkout/rates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/checkout'
    | '/checkout-success'
    | '/join'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/testing'
    | '/api/ipn'
    | '/products/$slug'
    | '/api/checkout/create'
    | '/api/checkout/rates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catalog'
    | '/checkout'
    | '/checkout-success'
    | '/join'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/testing'
    | '/api/ipn'
    | '/products/$slug'
    | '/api/checkout/create'
    | '/api/checkout/rates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  JoinRoute: typeof JoinRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestingRoute: typeof TestingRoute
  ApiIpnRoute: typeof ApiIpnRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiCheckoutCreateRoute: typeof ApiCheckoutCreateRoute
  ApiCheckoutRatesRoute: typeof ApiCheckoutRatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testing': {
      id: '/testing'
      path: '/testing'
      fullPath: '/testing'
      preLoaderRoute: typeof TestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ipn': {
      id: '/api/ipn'
      path: '/api/ipn'
      fullPath: '/api/ipn'
      preLoaderRoute: typeof ApiIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/rates': {
      id: '/api/checkout/rates'
      path: '/api/checkout/rates'
      fullPath: '/api/checkout/rates'
      preLoaderRoute: typeof ApiCheckoutRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout/create': {
      id: '/api/checkout/create'
      path: '/api/checkout/create'
      fullPath: '/api/checkout/create'
      preLoaderRoute: typeof ApiCheckoutCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  JoinRoute: JoinRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestingRoute: TestingRoute,
  ApiIpnRoute: ApiIpnRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiCheckoutCreateRoute: ApiCheckoutCreateRoute,
  ApiCheckoutRatesRoute: ApiCheckoutRatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
